### PR TITLE
Improve NG dataset reproducibility; pin torchmetrics

### LINKED ISSUE #550: Next-Gen Dataset: missing parameter in lightning module
## Describe the bug

I was trying to update the demo notebook for BSD and the NG Dataset, and ran into this issue:

```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[6], [line 7](vscode-notebook-cell:?execution_count=6&line=7)
      1 train_data_module = CareamicsDataModule(
      2     data_config=ng_data_config,
      3     train_data=train_files,
      4     val_data=val_files,
      5 )
----> [7](vscode-notebook-cell:?execution_count=6&line=7) model = N2VModule(config.algorithm_config)

File ~/git/careamics/careamics/src/careamics/lightning/dataset_ng/lightning_modules/n2v_module.py:37, in N2VModule.__init__(self, algorithm_config)
     28 def __init__(self, algorithm_config: Union[N2VAlgorithm, dict]) -> None:
     29     """Instantiate N2V DataModule.
     30 
     31     Parameters
   (...)     35         dictionary.
     36     """
---> [37](https://file+.vscode-resource.vscode-cdn.net/Users/joran.deschamps/git/careamics/careamics/src/careamics/dataset_ng/demos/~/git/careamics/careamics/src/careamics/lightning/dataset_ng/lightning_modules/n2v_module.py:37)     super().__init__(algorithm_config)
     39     assert isinstance(
     40         algorithm_config, N2VAlgorithm
     41     ), "algorithm_config must be a N2VAlgorithm"
     43     self.n2v_manipulate = N2VManipulateTorch(
     44         n2v_manipulate_config=algorithm_config.n2v_config
     45     )
...
     52 self._best_checkpoint_loaded = False
     54 # TODO: how to support metric evaluation better
---> [55](https://file+.vscode-resource.vscode-cdn.net/Users/joran.deschamps/git/careamics/careamics/src/careamics/dataset_ng/demos/~/git/careamics/careamics/src/careamics/lightning/dataset_ng/lightning_modules/unet_module.py:55) self.metrics = MetricCollection(PeakSignalNoiseRatio())

TypeError: PeakSignalNoiseRatio.__init__() missing 1 required positional argument: 'data_range'
```

`torcheval` has not had a new version in a while, so somehow we missed this?

@veegalinova

### PR DESCRIPTION
**Pull request by veegalinova**
## Description

These are small changes introduced in #546, split out from the work on patch filtering.
> [!NOTE]  
> **tldr**: small changes to dataloader defaults and seeding, pin `torchmetrics` version. 

### Overview - what changed?

1. Fix an issue with validation `num_workers` not being set from train parameters when it is specified
2. Improve reproducibility for NG dataset -  create a default random seed and propagate it to transforms
3. Pin `torchmetrics` to avoid a parameter error (see #550).

### Modified features or files

1. `data_model.py` and `ng_data_model.py`: Make a separate validator to set the validation `num_workers` from train params, if needed
2. `ng_data_model.py`: Set default random seed, make a new validator to propagate it to the transforms 
3. `pyproject.toml`: Add `torchmetrics>=0.11.0,<1.5.0`

## How has this been tested?

I ran `bsd68_demo.ipynb` with NGDataset to check reproducibility (epoch loss between runs) and parameter setting.

## Related Issues

- Resolves #550 

---

**Please ensure your PR meets the following requirements:**

- [ ] Code builds and passes tests locally, including doctests
- [ ] New tests have been added (for bug fixes/features)
- [ ] Pre-commit passes
- [ ] PR to the documentation exists (for bug fixes / features)

### CODE REVIEW

**Review by jdeschamps — APPROVED** [review]
Great, thanks!

Should we add a todo/issue to change the metrics to some scale invariable one? That would lift the constraint on torchmetrics.

**Comment by veegalinova** [comment]
> Great, thanks!
> 
> Should we add a todo/issue to change the metrics to some scale invariable one? That would lift the constraint on torchmetrics.

I created an issue - https://github.com/CAREamics/careamics/issues/568
